version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=bogdan
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=humanresources2